// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hedgehog/protocol/proto/servo.proto

#include "hedgehog/protocol/proto/servo.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace hedgehog {
namespace protocol {
namespace proto {

inline constexpr ServoAction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : port_{0u},
        active_{false},
        position_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ServoAction::ServoAction(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ServoActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServoActionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServoActionDefaultTypeInternal() {}
  union {
    ServoAction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServoActionDefaultTypeInternal _ServoAction_default_instance_;

inline constexpr ServoCommandMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        subscription_{nullptr},
        port_{0u},
        active_{false},
        position_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR ServoCommandMessage::ServoCommandMessage(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ServoCommandMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServoCommandMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServoCommandMessageDefaultTypeInternal() {}
  union {
    ServoCommandMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServoCommandMessageDefaultTypeInternal _ServoCommandMessage_default_instance_;
}  // namespace proto
}  // namespace protocol
}  // namespace hedgehog
static ::_pb::Metadata file_level_metadata_hedgehog_2fprotocol_2fproto_2fservo_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_hedgehog_2fprotocol_2fproto_2fservo_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_hedgehog_2fprotocol_2fproto_2fservo_2eproto = nullptr;
const ::uint32_t TableStruct_hedgehog_2fprotocol_2fproto_2fservo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoAction, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoAction, _impl_.port_),
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoAction, _impl_.active_),
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoAction, _impl_.position_),
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoCommandMessage, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoCommandMessage, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoCommandMessage, _impl_.port_),
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoCommandMessage, _impl_.active_),
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoCommandMessage, _impl_.position_),
    PROTOBUF_FIELD_OFFSET(::hedgehog::protocol::proto::ServoCommandMessage, _impl_.subscription_),
    ~0u,
    ~0u,
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::hedgehog::protocol::proto::ServoAction)},
        {11, 23, -1, sizeof(::hedgehog::protocol::proto::ServoCommandMessage)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::hedgehog::protocol::proto::_ServoAction_default_instance_._instance,
    &::hedgehog::protocol::proto::_ServoCommandMessage_default_instance_._instance,
};
const char descriptor_table_protodef_hedgehog_2fprotocol_2fproto_2fservo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n#hedgehog/protocol/proto/servo.proto\022\027h"
    "edgehog.protocol.proto\032*hedgehog/protoco"
    "l/proto/subscription.proto\"=\n\013ServoActio"
    "n\022\014\n\004port\030\001 \001(\r\022\016\n\006active\030\002 \001(\010\022\020\n\010posit"
    "ion\030\003 \001(\r\"\202\001\n\023ServoCommandMessage\022\014\n\004por"
    "t\030\001 \001(\r\022\016\n\006active\030\002 \001(\010\022\020\n\010position\030\003 \001("
    "\r\022;\n\014subscription\030\004 \001(\0132%.hedgehog.proto"
    "col.proto.SubscriptionB)\n\037at.pria.hedgeh"
    "og.protocol.protoB\006ServoPb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto_deps[1] =
    {
        &::descriptor_table_hedgehog_2fprotocol_2fproto_2fsubscription_2eproto,
};
static ::absl::once_flag descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto = {
    false,
    false,
    353,
    descriptor_table_protodef_hedgehog_2fprotocol_2fproto_2fservo_2eproto,
    "hedgehog/protocol/proto/servo.proto",
    &descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto_once,
    descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_hedgehog_2fprotocol_2fproto_2fservo_2eproto::offsets,
    file_level_metadata_hedgehog_2fprotocol_2fproto_2fservo_2eproto,
    file_level_enum_descriptors_hedgehog_2fprotocol_2fproto_2fservo_2eproto,
    file_level_service_descriptors_hedgehog_2fprotocol_2fproto_2fservo_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto_getter() {
  return &descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_hedgehog_2fprotocol_2fproto_2fservo_2eproto(&descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto);
namespace hedgehog {
namespace protocol {
namespace proto {
// ===================================================================

class ServoAction::_Internal {
 public:
};

ServoAction::ServoAction(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:hedgehog.protocol.proto.ServoAction)
}
ServoAction::ServoAction(
    ::google::protobuf::Arena* arena, const ServoAction& from)
    : ServoAction(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ServoAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ServoAction::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, port_),
           0,
           offsetof(Impl_, position_) -
               offsetof(Impl_, port_) +
               sizeof(Impl_::position_));
}
ServoAction::~ServoAction() {
  // @@protoc_insertion_point(destructor:hedgehog.protocol.proto.ServoAction)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ServoAction::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ServoAction::Clear() {
// @@protoc_insertion_point(message_clear_start:hedgehog.protocol.proto.ServoAction)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.port_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.position_) -
      reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.position_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ServoAction::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ServoAction::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ServoAction_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 port = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServoAction, _impl_.port_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ServoAction, _impl_.port_)}},
    // bool active = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ServoAction, _impl_.active_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ServoAction, _impl_.active_)}},
    // uint32 position = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServoAction, _impl_.position_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ServoAction, _impl_.position_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 port = 1;
    {PROTOBUF_FIELD_OFFSET(ServoAction, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bool active = 2;
    {PROTOBUF_FIELD_OFFSET(ServoAction, _impl_.active_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // uint32 position = 3;
    {PROTOBUF_FIELD_OFFSET(ServoAction, _impl_.position_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ServoAction::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hedgehog.protocol.proto.ServoAction)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_port(), target);
  }

  // bool active = 2;
  if (this->_internal_active() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_active(), target);
  }

  // uint32 position = 3;
  if (this->_internal_position() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_position(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hedgehog.protocol.proto.ServoAction)
  return target;
}

::size_t ServoAction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hedgehog.protocol.proto.ServoAction)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_port());
  }

  // bool active = 2;
  if (this->_internal_active() != 0) {
    total_size += 2;
  }

  // uint32 position = 3;
  if (this->_internal_position() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_position());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ServoAction::_class_data_ = {
    ServoAction::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ServoAction::GetClassData() const {
  return &_class_data_;
}

void ServoAction::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ServoAction*>(&to_msg);
  auto& from = static_cast<const ServoAction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hedgehog.protocol.proto.ServoAction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_active() != 0) {
    _this->_internal_set_active(from._internal_active());
  }
  if (from._internal_position() != 0) {
    _this->_internal_set_position(from._internal_position());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServoAction::CopyFrom(const ServoAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hedgehog.protocol.proto.ServoAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ServoAction::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ServoAction::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ServoAction::InternalSwap(ServoAction* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServoAction, _impl_.position_)
      + sizeof(ServoAction::_impl_.position_)
      - PROTOBUF_FIELD_OFFSET(ServoAction, _impl_.port_)>(
          reinterpret_cast<char*>(&_impl_.port_),
          reinterpret_cast<char*>(&other->_impl_.port_));
}

::google::protobuf::Metadata ServoAction::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto_getter, &descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto_once,
      file_level_metadata_hedgehog_2fprotocol_2fproto_2fservo_2eproto[0]);
}
// ===================================================================

class ServoCommandMessage::_Internal {
 public:
  using HasBits = decltype(std::declval<ServoCommandMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_._has_bits_);
  static const ::hedgehog::protocol::proto::Subscription& subscription(const ServoCommandMessage* msg);
  static void set_has_subscription(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::hedgehog::protocol::proto::Subscription& ServoCommandMessage::_Internal::subscription(const ServoCommandMessage* msg) {
  return *msg->_impl_.subscription_;
}
void ServoCommandMessage::clear_subscription() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.subscription_ != nullptr) _impl_.subscription_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
ServoCommandMessage::ServoCommandMessage(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:hedgehog.protocol.proto.ServoCommandMessage)
}
inline PROTOBUF_NDEBUG_INLINE ServoCommandMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

ServoCommandMessage::ServoCommandMessage(
    ::google::protobuf::Arena* arena,
    const ServoCommandMessage& from)
    : ::google::protobuf::Message(arena) {
  ServoCommandMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.subscription_ = (cached_has_bits & 0x00000001u)
                ? CreateMaybeMessage<::hedgehog::protocol::proto::Subscription>(arena, *from._impl_.subscription_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, port_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, port_),
           offsetof(Impl_, position_) -
               offsetof(Impl_, port_) +
               sizeof(Impl_::position_));

  // @@protoc_insertion_point(copy_constructor:hedgehog.protocol.proto.ServoCommandMessage)
}
inline PROTOBUF_NDEBUG_INLINE ServoCommandMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ServoCommandMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, subscription_),
           0,
           offsetof(Impl_, position_) -
               offsetof(Impl_, subscription_) +
               sizeof(Impl_::position_));
}
ServoCommandMessage::~ServoCommandMessage() {
  // @@protoc_insertion_point(destructor:hedgehog.protocol.proto.ServoCommandMessage)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ServoCommandMessage::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  delete _impl_.subscription_;
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ServoCommandMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:hedgehog.protocol.proto.ServoCommandMessage)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.subscription_ != nullptr);
    _impl_.subscription_->Clear();
  }
  ::memset(&_impl_.port_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.position_) -
      reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.position_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ServoCommandMessage::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2> ServoCommandMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ServoCommandMessage_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // .hedgehog.protocol.proto.Subscription subscription = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 0, PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.subscription_)}},
    // uint32 port = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServoCommandMessage, _impl_.port_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.port_)}},
    // bool active = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ServoCommandMessage, _impl_.active_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.active_)}},
    // uint32 position = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServoCommandMessage, _impl_.position_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.position_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 port = 1;
    {PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.port_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bool active = 2;
    {PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.active_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // uint32 position = 3;
    {PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.position_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // .hedgehog.protocol.proto.Subscription subscription = 4;
    {PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.subscription_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::hedgehog::protocol::proto::Subscription>()},
  }}, {{
  }},
};

::uint8_t* ServoCommandMessage::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:hedgehog.protocol.proto.ServoCommandMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this->_internal_port(), target);
  }

  // bool active = 2;
  if (this->_internal_active() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_active(), target);
  }

  // uint32 position = 3;
  if (this->_internal_position() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_position(), target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .hedgehog.protocol.proto.Subscription subscription = 4;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, _Internal::subscription(this),
        _Internal::subscription(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hedgehog.protocol.proto.ServoCommandMessage)
  return target;
}

::size_t ServoCommandMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hedgehog.protocol.proto.ServoCommandMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .hedgehog.protocol.proto.Subscription subscription = 4;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.subscription_);
  }

  // uint32 port = 1;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_port());
  }

  // bool active = 2;
  if (this->_internal_active() != 0) {
    total_size += 2;
  }

  // uint32 position = 3;
  if (this->_internal_position() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_position());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ServoCommandMessage::_class_data_ = {
    ServoCommandMessage::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ServoCommandMessage::GetClassData() const {
  return &_class_data_;
}

void ServoCommandMessage::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ServoCommandMessage*>(&to_msg);
  auto& from = static_cast<const ServoCommandMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:hedgehog.protocol.proto.ServoCommandMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_subscription()->::hedgehog::protocol::proto::Subscription::MergeFrom(
        from._internal_subscription());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  if (from._internal_active() != 0) {
    _this->_internal_set_active(from._internal_active());
  }
  if (from._internal_position() != 0) {
    _this->_internal_set_position(from._internal_position());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServoCommandMessage::CopyFrom(const ServoCommandMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hedgehog.protocol.proto.ServoCommandMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ServoCommandMessage::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ServoCommandMessage::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ServoCommandMessage::InternalSwap(ServoCommandMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.position_)
      + sizeof(ServoCommandMessage::_impl_.position_)
      - PROTOBUF_FIELD_OFFSET(ServoCommandMessage, _impl_.subscription_)>(
          reinterpret_cast<char*>(&_impl_.subscription_),
          reinterpret_cast<char*>(&other->_impl_.subscription_));
}

::google::protobuf::Metadata ServoCommandMessage::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto_getter, &descriptor_table_hedgehog_2fprotocol_2fproto_2fservo_2eproto_once,
      file_level_metadata_hedgehog_2fprotocol_2fproto_2fservo_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace protocol
}  // namespace hedgehog
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
